version: '3'

services:
  filestorage:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY}"
    ports:
      - "${STORAGE_PORT}:9000"
      - "${STORAGE_CONSOLE_PORT}:9001"
    command: server /data --console-address ":9001"
  
  chat:
    image: centrifugo/centrifugo:v5
    volumes:
      - ./chat_config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8183:8000"

  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MARIADB_DATABASE: "${DATABASE_NAME}"

  backend:
    build: .
    environment:
      DJANGO_SUPERUSER_PASSWORD: "${ADMIN_PASSWORD}"
      DJANGO_SUPERUSER_USERNAME: "${ADMIN_USER}"
      DJANGO_SUPERUSER_EMAIL: "${ADMIN_EMAIL}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_HOST: "db"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_ENDPOINT: "http://filestorage:9000"
      S3_BUCKET: "concertstreaming"
      S3_PUBLIC_URL: "${S3_PUBLIC_URL}"
      CENTRIFUGO_SERVER: "http://chat:8000"
      CENTRIFUGO_API_KEY: "DW6XQJYKQT22DUS2GOOGPLBOBV66STNBDISKPS5UEZ52NXKO"
    depends_on:
      - db
      - filestorage
      - chat
    ports:
      - "${BACKEND_PORT}:8080"