# Generated by Django 4.2.9 on 2024-01-26 09:08

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("slots", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        default=api.models.UserRole["VIEWER"], max_length=40
                    ),
                ),
            ],
        ),
    ]
