# Generated by Django 4.2.9 on 2024-01-30 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_concert_created_at_concert_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link="sessions",
                        to="api.extendeduser",
                    ),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link="sessions",
                        to="api.concert",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="concert",
            name="poster_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="concert",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
