# Generated by Django 4.2.9 on 2024-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_artistsession_concert_poster_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="concert",
            name="status",
            field=models.CharField(default="scheduled", max_length=20),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="avatar_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="name",
            field=models.CharField(default="User", max_length=200),
        ),
    ]
