# Generated by Django 4.2.9 on 2024-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_concert_category_concert_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistsession",
            name="stream_key",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="concert",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("finished", "Finished"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
