# Generated by Django 4.2.9 on 2024-02-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_artistsession_stream_key_alter_concert_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistsession",
            name="artist_demo_url",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="artistsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "token",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("expire_at", models.BigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.extendeduser",
                    ),
                ),
            ],
        ),
    ]
