# Generated by Django 4.2.9 on 2024-02-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_concertsubscription_artistsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="concert_subscribers",
            field=models.ManyToManyField(
                through="api.ConcertSubscription", to="api.concert"
            ),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="follower_subscribers",
            field=models.ManyToManyField(
                through="api.ArtistSubscription", to="api.extendeduser"
            ),
        ),
        migrations.AlterField(
            model_name="concertsubscription",
            name="concert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to="api.concert",
            ),
        ),
        migrations.AddConstraint(
            model_name="artistsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "artist"), name="artist_subscription_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="concertsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "concert"), name="concert_subscription_unique"
            ),
        ),
    ]
