# Generated by Django 4.2.9 on 2024-02-20 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_extendeduser_concert_subscribers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendeduser",
            old_name="concert_subscribers",
            new_name="concerts_followed",
        ),
        migrations.RenameField(
            model_name="extendeduser",
            old_name="follower_subscribers",
            new_name="subscribers",
        ),
        migrations.AddField(
            model_name="concert",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="concert_subscribers",
                through="api.ConcertSubscription",
                to="api.extendeduser",
            ),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="artists_followed",
            field=models.ManyToManyField(
                through="api.ArtistSubscription", to="api.extendeduser"
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="concert",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concert_admin",
                to="api.extendeduser",
            ),
        ),
    ]
