# Generated by Django 4.2.9 on 2024-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0009_rename_concert_subscribers_extendeduser_concerts_followed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="access",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid")],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="concert",
            name="performance_time",
            field=models.IntegerField(default=15),
        ),
    ]
