# Generated by Django 4.2.9 on 2024-02-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_concert_access_concert_performance_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
