# Generated by Django 4.2.9 on 2024-02-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_extendeduser_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistsession",
            name="concert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="performances",
                to="api.concert",
            ),
        ),
        migrations.AlterField(
            model_name="artistsession",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="performances",
                to="api.extendeduser",
            ),
        ),
    ]
