# Generated by Django 4.2.9 on 2024-02-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_sponsorad_artistsubscription_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="artist_genre",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
