# Generated by Django 4.2.9 on 2024-02-26 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_extendeduser_artist_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcertTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        related_name="tickets",
                        to="api.extendeduser",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("issued", "Issued"), ("activated", "Activated")],
                        default="issued",
                        max_length=20,
                    ),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.concert"
                    ),
                ),
            ],
        ),
    ]
