# Generated by Django 4.2.9 on 2024-02-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_concertticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concertticket",
            name="concert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="ticket",
                to="api.concert",
            ),
        ),
    ]
