# Generated by Django 4.2.9 on 2024-02-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_concertticket_concert"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="concertticket",
            constraint=models.UniqueConstraint(
                fields=("user", "concert"), name="concert_ticket_unique"
            ),
        ),
    ]
