# Generated by Django 4.2.9 on 2024-02-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_concertticket_concert_ticket_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
